# Copyright (C) 2019 DevOps, SIA. - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the Apache License Version 2.0.
# http://www.apache.org/licenses

---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    java_packages:
      - openjdk-11-jdk
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
