# Copyright (C) 2019 DevOps, SIA. - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the Apache License Version 2.0.
# http://www.apache.org/licenses

---
- hosts: all
  become: yes
  become_method: sudo
  vars:
    java_packages:
      - openjdk-11-jdk
    jenkins_java_options: "-Djenkins.install.runSetupWizard=false"

    nginx_remove_default_vhost: true
    nginx_vhosts:
      - listen: "80 default_server"
        server_name: "localhost"
        state: "present"
        filename: "jenkins.conf"
        extra_parameters: |
          server_tokens off;

          if ($http_x_forwarded_proto = 'http') {
            return 301 https://$host$request_uri;
          }

          set_real_ip_from  10.0.0.0/8;
          set_real_ip_from  172.16.0.0/12;
          real_ip_header    X-Forwarded-For;
          real_ip_recursive on;

          location / {
            proxy_set_header        Host              $host;
            proxy_set_header        X-Real-IP         $remote_addr;
            proxy_set_header        X-Forwarded-For   $proxy_add_x_forwarded_for;
            proxy_set_header        X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_set_header        X-Forwarded-Port  $http_x_forwarded_port;

            proxy_pass              http://localhost:8080;

            proxy_http_version      1.1;
            proxy_request_buffering off;
          }

  roles:
    - geerlingguy.nginx
    - geerlingguy.java
    - geerlingguy.jenkins
