# Copyright (C) 2019 DevOps, SIA. - All Rights Reserved
# You may use, distribute and modify this code under the
# terms of the Apache License Version 2.0.
# http://www.apache.org/licenses

---
- name: geerlingguy.jenkins
  version: 4.2.1
- name: geerlingguy.java
  version: 1.9.7
